---
driver:
  name: digitalocean
  flavor: 4GB

platforms:
  - name: ubuntu-12.04

provisioner:
   name: chef_zero
   data_bags_path: <%= File.expand_path('../../data_bags') %>
   encrypted_data_bags_path: <%= File.expand_path('../../data_bags') %>

suites:
  - name: controller
    run_list:
      - recipe[deis::controller]
    attributes:
    data_bags_path: "test/integration/controller/data_bags"
